[[Images]]
Name = "zeekozhu/aspnetcore-build-yarn"
Tag = "zeekozhu/aspnetcore-build-yarn"
TestImage = "zeekozhu/aspnetcore-build-yarn:tmp"
Dotnet = "2.2.103"
Node = "v10.14.1"
Yarn = "1.12.3"
Sdk = true
Suffix = ""
Latest = true
SkipTest = false

[[Images]]
Name = "zeekozhu/aspnetcore-build-yarn:chromium"
Tag = "zeekozhu/aspnetcore-build-yarn"
TestImage = "zeekozhu/aspnetcore-build-yarn:tmp-chromium"
Dotnet = "2.2.103"
Node = "v10.14.1"
Yarn = "1.12.3"
Sdk = true
Suffix = "chromium"
Latest = false
SkipTest = false

[[Images]]
Name = "zeekozhu/aspnetcore-node"
Tag = "zeekozhu/aspnetcore-node"
TestImage = "zeekozhu/aspnetcore-node:tmp"
Dotnet = "2.2.1"
Node = "v10.14.1"
Yarn = "1.12.3"
Sdk = false
Suffix = ""
Latest = true
SkipTest = false

[[Images]]
Name = "zeekozhu/aspnetcore-node:alpine"
Tag = "zeekozhu/aspnetcore-node"
TestImage = "zeekozhu/aspnetcore-node:tmp-alpine"
Dotnet = "2.2.1"
Node = "v10.14.1"
Yarn = "1.12.3"
Sdk = false
Suffix = "alpine"
Latest = false
SkipTest = false

[[Images]]
Name = "zeekozhu/aspnetcore-build-yarn:alpine"
Tag = "zeekozhu/aspnetcore-build-yarn"
TestImage = "zeekozhu/aspnetcore-build-yarn:tmp-alpine"
Dotnet = "2.2.103"
Node = "v10.14.1"
Yarn = "1.12.3"
Sdk = true
Suffix = "alpine"
Latest = false
SkipTest = false

[[Images]]
Name = "zeekozhu/aspnetcore-node-deps"
Tag = "zeekozhu/aspnetcore-node-deps"
TestImage = "zeekozhu/aspnetcore-node-deps:tmp"
Dotnet = "2.2.1"
Node = "v10.14.1"
Yarn = "1.12.3"
Sdk = true
Suffix = ""
Latest = false
SkipTest = true
